const mongoose = require('mongoose');
const { v4: uuidv4 } = require('uuid'); // Import UUID to generate unique codes

const itemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  price: { type: Number, required: true },
  totalAmount: { type: Number, required: true },
  commission: { type: Number, required: true },
  picture: { type: String, required: true },
  createdAt: { type: Date, default: Date.now }, // Add createdAt field
  uniqueCode: { type: String, required: true, unique: true, default: uuidv4 }, // Add uniqueCode field with default value generated by uuidv4
  status: { type: String, default: "available" } // Track item's purchase and confirmation status
});

itemSchema.pre('save', function(next) {
  if (!this.uniqueCode) {
    this.uniqueCode = uuidv4(); // Ensure uniqueCode is set before saving
  }
  next();
});

const Item = mongoose.model('Item', itemSchema);

module.exports = Item;